<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>ConfigForge.Core.CapabilityProxy</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../ConfigForge.Abstractions/ConfigForge.Abstractions.csproj" />
  </ItemGroup>
</Project>
